version: '2'

services:
  web:
    container_name: 'web-app'
    image: teamonelocal/production
    links:
    - db
    depends_on:
    - db
    ports:
    - "80:8000"
    volumes:
    - .:/usr/src/app/
    environment:
    - NODE_ENV=production
    - MONGO_URL=mongodb://db:27017/todo-v2
    - SECRET=T@5kM4nag3R
  db:
    image: mongo:latest
    ports:
    - "27017:27017"

