version: '2'

services:
  web:
    container_name: 'web-app'
    image: teamonelocal/production
    ports:
    - "80:8000"
    volumes:
    - .:/usr/src/app/
    environment:
    - NODE_ENV=production
    - MONGO_URL=mongodb://172.31.26.90:27017/todo-v2
    - SECRET=T@5kM4nag3R